#!/bin/dash
# Written By Marko Wong (z5309371)
# Girt-log prints a line for every commit made to the repository: each line 
# should contain the commit number, and the commit message.

# There have to be a existing .girt repository
if [ -d .girt ]
then :
else 
    echo "girt-log: error: girt repository directory .girt not found"
    exit 1;
fi

if [ $# -ne 0 ]
then 
    echo "usage: girt-log"
    exit 1;
fi

for directories in .girt/*
do
    if echo "$directories" | egrep -q '^.girt/commit_.$' && [ -d "$directories" ]
    then
        echo -n "$directories" | sed 's/.*commit_/''/g'
        echo -n " "
        cat "$directories/commit_message.txt"
    fi
done | sort -r;
exit 0;
