#!/bin/dash

if [ $# -lt 1 ]
then
    echo "usage: girt-add <filenames>"
    exit 1;
fi
if [ -d .girt ] || [ -d .girt/adds ]
then 
    for file in $@
    do
        if [ -f "$file" ] || [ -f .girt/adds/"$file" ] # &&  echo "$file" | egrep -q ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
        then 
            :
        else
            echo "girt-add: error: can not open '"$file"'";
            exit 1;
        fi
    done
else
    echo "girt-add: error: girt repository directory .girt not found"
    exit 1;
fi

for file in $@
do
    # adding the file if it exists in the cwd
    if [ -f "$file" ] # &&  echo "$file" | egrep -q ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
    then 
        cp "$file" ".girt/adds";
    # removing a file if it is not in cwd but in .girt/adds
    elif [ -f .girt/adds/"$file" ] 
    then
        rm .girt/adds/"$file";
    else
        echo "girt-add: error: can not open '"$file"'";
        exit 1;
    fi
done
exit 0;
