#!/bin/dash

if [ -d .girt ]
then :
else 
    echo "girt-log: error: girt repository directory .girt not found"
    exit 1;
fi

for directories in .girt/*
do
    if echo "$directories" | egrep -q '^.girt/commit_.$' && [ -d "$directories" ]
    then
        echo -n "$directories" | sed 's/.*commit_/''/g'
        echo -n " "
        cat "$directories/commit_message.txt"
    fi
done | sort -r;
exit 0;