#!/bin/dash

if [ -d .girt ]
then :
else 
    echo "girt-commit: error: girt repository directory .girt not found"
    exit 1;
fi

if [ -d .girt/commit_0 ]
then
    :
else
    echo "girt-branch: error: this command can not be run until after the first commit"
    exit 1;
fi

if [ $# -eq 0 ]
then 
    #list branches
    (for branches in .girt/branches/*
    do
        if [ -d "$branches" ]
        then 
            b_name=$(basename="$branches");
            echo "$b_name";
        fi
    done
    echo "master";)|sort;

elif [ $# -eq 1 ] && [ "$1" = "-d" ]
then 
    echo "error girt-branch: error: branch name required";
    exit 1;

elif [ $# -eq 1 ] && echo "$1" | egrep -q '^-.*'
then 
    echo "usage: girt-branch [-d] <branch>";
    exit 1;

elif [ $# -eq 1 ] && echo "$1" | egrep -q '^[^a-zA-Z].*'
then 
    echo "girt-branch: error: invalid branch name '"$1"'";
    exit 1;

elif [ $# -eq 1 ]
then 
    #create that branch
    if [ -d .girt/branches/"$1" ]
    then 
        echo "girt-branch: error: branch '"$1"' already exists";
        exit 1;
    else
        mkdir .girt/branches/"$1";
        #echo "making branch "$1"";
        for file in *
        do
            if [ -f "$file" ]
            then
                cp "$file" .girt/branches/"$1"/"$file";
            fi
        done
    fi
elif [ $# -eq 2 ] && [ "$1" = "-d" ] &&  echo "$2" | egrep -q '^[a-zA-Z].*'
then
    #delete that branch
    if [ -d .girt/branches/"$2" ]
    then 
        rm -r .girt/branches/"$2";
    elif [ "$2" = "master" ]
    then
        echo "girt-branch: error: can not delete branch 'master'"
        exit 1;
    else
        echo "girt-branch: error: branch '"$2"' doesn't exist";
        exit 1;
    fi
elif [ $# -eq 2 ] && [ "$1" = "-d" ] && echo "$2" | egrep -q '^[^a-zA-Z].*'
then 
    echo "girt-branch: error: invalid branch name '"$2"'";
    exit 1;

else
    echo "usage: girt-branch [-d] <branch>";
    exit 1;
fi
