#!/bin/dash
# Written By Marko Wong (z5309371)
# Girt-show prints the contents of the specified filename as of the specified commit. 
# If commit is omitted, the contents of the file in the index should be printed.

# There have to be a existing .girt repository
if [ -d .girt ]
then :
else 
    echo "girt-show: error: girt repository directory .girt not found"
    exit 1;
fi

# There can be only one argument
if [ $# -ne 1 ]
then
    echo "usage: girt-show <commit>:<filename>"
    exit 1;
fi

# There is a missing ':'
if echo "$1" | egrep -q ':'
then
    :
else
    echo "girt-show: error: invalid object "$1"";
    exit 1;
fi

# Extract the info from argument and assign it to a variable
commit_index=$(echo "$1" | sed 's/:.*$/''/g');
filename=$(echo "$1" | sed 's/^.*:/''/g');

# if there is no commit number then print out contents from index
if [ -z "$commit_index" ]
then
    if [ -f ".girt/index/"$filename"" ]
    then
        cat ".girt/index/"$filename"";
        exit 0;
    else 
        echo "girt-show: error: '"$filename"' not found in index"
        exit 1;
    fi
fi

# Check if the commit number is valid
if [ -d ".girt/commit_"$commit_index"" ] 
then
    :   
else
    echo "girt-show: error: unknown commit '"$commit_index"'";
    exit 1;
fi

# if there is a commit number then print out contents from that commit number
if [ -f ".girt/commit_"$commit_index"/"$filename"" ]
then
    cat .girt/commit_"$commit_index"/"$filename";
    exit 0;
else
    echo "girt-show: error: '"$filename"' not found in commit "$commit_index"";
    exit 1;
fi
