#!/bin/dash

if [ -d .girt ]
then :
else 
    echo "girt-commit: error: girt repository directory .girt not found"
    exit 1;
fi

if [ -d .girt/commit_0 ]
then
    :
else
    echo "girt-branch: error: this command can not be run until after the first commit"
    exit 1;
fi

if [ $# -eq 1 ]
then
    cwb=$(cat .girt/branches/current_working_branch.txt);
    #echo "switch from "$cwb"";
    # valid branch
    if [ -d .girt/branches/"$1" ]
    then 
        if [ "$1" = "$cwb" ]
        then
            echo "Already on '"$1"'";
            exit 1;
        fi
    
        # sync the branch you are swtiching from with cwd
        for current_files in ./*
        do
            if [ -f "$current_files" ]
            then
                current_file_name=$(basename "$branch_files");
                #echo "copying "$current_files" to .girt/branches/"$cwb"/"$current_file_name"";
                cp "$current_files" .girt/branches/"$cwb"/"$current_file_name";

                cp "$current_files" .girt/branches/"$1"/"$current_file_name";
            fi
        done

        #calculate the commit number in cwd
        commit_no=0;
        while [ -d ".girt/commit_"$commit_no"" ] 
        do
            commit_no=$(( $commit_no + 1 ));
        done

        cwb_latest_commit_no=$(( $commit_no - 1 ));

        #track the lastest commit within a branch
        echo "$cwb_latest_commit_no" > .girt/branches/"$cwb"/latest_commit_no.txt;

        #remove all files in cwd to be updated with new branch
        for files in ./*
        do
            if [ -f "$files" ]
            then
                file_name=$(basename "$files");
                rm "$files";
            fi
        done

        # copy files from branch to cwd
        for branch_files in .girt/branches/"$1"/*
        do
            branch_file_name=$(basename "$branch_files");
            if [ -f "$branch_files" ] && [ "$branch_file_name" != "latest_commit_no.txt" ]
            then
                #echo "copying "$branch_files" to ./"$branch_file_name""; 
                cp "$branch_files" ./"$branch_file_name" ;
            fi
        done

        # detect any the diff between the latest commits of branches
        cwb_commit_no=$(cat .girt/branches/"$cwb"/latest_commit_no.txt);
        new_commit_no=$(cat .girt/branches/"$1"/latest_commit_no.txt);
        diff ".girt/branches/"$cwb"/latest_commit_no.txt" ".girt/branches/"$1"/latest_commit_no.txt" >/dev/null 2>/dev/null;
        if [ $? -ne 0 ]
        then
            #echo "difference_detected";
        
            # update branch (the one we are switching to) with it's own commit
            for branch_files in .girt/commit_"$new_commit_no"/*
            do
                branch_file_name=$(basename "$branch_files");
                if [ -f "$branch_files" ] && [ "$branch_file_name" != "commit_message.txt" ]
                then
                    cp "$branch_files" ./"$branch_file_name" ;
                fi
            done
        fi
        # elif [ diff from all three places  ] 
        # then 
        #     echo" error overwrite error";
        #     exit 1;

        # update the current working branch
        echo "$1" > .girt/branches/current_working_branch.txt;
        echo "Switched to branch '"$1"'";
    else
        echo "girt-checkout: error: unknown branch '"$1"'";
    fi
else
    echo "usage: girt-checkout <branch>"
fi
