#!/bin/dash

(
#calculate the commit number
commit_no=0;
while [ -d ".girt/commit_"$commit_no"" ] 
do
    commit_no=$(( $commit_no + 1 ));
done

latest_commit_no=$(( $commit_no - 1 ));

for file in *
do
    if [ -f "$file" ]
    then
        if [ -f .girt/adds/"$file" ] && [ -f .girt/commit_"$latest_commit_no"/"$file" ]
        then
            adds_diff_repo=1;
            cwd_diff_repo=1;
            cwd_diff_adds=1;
            # checking for unsaved changes in .girt/adds (#adds vs commit)
            diff -s ".girt/adds/"$file"" ".girt/commit_"$latest_commit_no"/"$file"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                adds_diff_repo=0;
            fi

            # checking for unsaved changes in cwd  (#cwd vs commit)
            diff -s "./"$file"" ".girt/commit_"$latest_commit_no"/"$file"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                cwd_diff_repo=0; 
            fi

            # checking for unsaved changes in .girt/adds  (#cwd vs adds)
            diff -s "./"$file"" ".girt/adds/"$file"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                cwd_diff_adds=0; 
            fi

            if [ "$adds_diff_repo" -eq 0 ] && [ "$cwd_diff_repo" -eq 0 ] && [ "$cwd_diff_adds" -eq 0 ]
            then 
                echo ""$file" - file changed, different changes staged for commit";

            elif [ "$adds_diff_repo" -eq 0 ] && [ "$cwd_diff_repo" -eq 0 ]
            then
                echo ""$file" - file changed, changes staged for commit";
                
            elif [ "$cwd_diff_repo" -eq 0 ] && [ "$cwd_diff_adds" -eq 0 ]
            then 
                echo ""$file" - file changed, changes not staged for commit";
            else
                echo ""$file" - same as repo";
            fi

        elif [ -f .girt/adds/"$file" ]
        then 
            diff -s "./"$file"" ".girt/adds/"$file"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                echo ""$file" - added to index, file changed";
            else
                echo ""$file" - added to index";
            fi
        elif [ -f .girt/commit_"$latest_commit_no"/"$file" ]
        then 
            echo ""$file" - untracked";
        else
            echo ""$file" - untracked";
        fi
    fi
done 

#check files that are not in cwd but in adds
for adds_file in .girt/adds/*
do
    adds_file_name=$(basename "$adds_file");
    if [ -f ./"$adds_file_name" ]
    then
        :
    else
        #echo "checking "$adds_file_name"";
        if [ -f .girt/adds/"$adds_file_name" ] && [ -f .girt/commit_"$latest_commit_no"/"$adds_file_name" ]
        then
            diff -s ".girt/adds/"$adds_file_name"" ".girt/commit_"$latest_commit_no"/"$adds_file_name"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                echo ""$adds_file_name" - file deleted, different changes staged for commit";
            else
                echo ""$adds_file_name" - file deleted";
            fi
        elif [ -f .girt/adds/"$adds_file_name" ]
        then
            echo ""$adds_file_name" - added to index, file deleted";
        fi
    fi
done 

#check files that are only in the latest commit
for commit_file in .girt/commit_"$latest_commit_no"/*
do
    commit_file_name=$(basename "$commit_file");
    if [ -f ./"$commit_file_name" ] || [ -f .girt/adds/"$commit_file_name" ] || [ "$commit_file_name" = "commit_message.txt" ]
    then
        :
    else
        #echo "checking "$commit_file_name"";
        if [ -f .girt/commit_"$latest_commit_no"/"$commit_file_name" ]
        then
            echo ""$commit_file_name" - deleted";
        fi
    fi
done 
)|sort
