#!/bin/dash

if [ -d .girt ]
then :
else 
    echo "girt-rm: error: girt repository directory .girt not found"
    exit 1;
fi

# usage check
if [ $# -lt 1 ]
then
    echo "usage: girt-rm [--force] [--cached] <filenames>";
    exit 1;
elif [ $# -eq 1 ] && ([ $1 = "--force" ] || [ $1 = "--cached" ])
then 
    echo "usage: girt-rm [--force] [--cached] <filenames>";
    exit 1;
elif [ $# -eq 2 ] && [ $1 = "--force" ] && [ $2 = "--cached" ]
then 
    echo "usage: girt-rm [--force] [--cached] <filenames>";
    exit 1;
fi

#calculate the commit number
commit_no=0;
while [ -d ".girt/commit_"$commit_no"" ] 
do
    commit_no=$(( $commit_no + 1 ));
done

prev_commit_no=$(( $commit_no - 1 ));

# remove specified file from index
for file in $@
do
    if [ -f .girt/index/"$file" ] || [ -f .girt/commit_"$prev_commit_no"/"$file" ] 
    then 
        index_diff_repo=1;
        cwd_diff_repo=1;
        cwd_diff_index=1;

        # normal checking
        if [ "$1" != "--force" ] && [ "$1" != "--cached" ] && [ "$2" != "--cached" ]
        then
            # checking for unsaved changes in .girt/index (#index vs commit)
            diff -s ".girt/index/$file" ".girt/commit_"$prev_commit_no"/"$file"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                index_diff_repo=0;
            fi

            # checking for unsaved changes in cwd  (#cwd vs commit)
            diff -s "./"$file"" ".girt/commit_"$prev_commit_no"/"$file"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                cwd_diff_repo=0; 
            fi

            # checking for unsaved changes in .girt/index  (#cwd vs index)
            diff -s "./"$file"" ".girt/index/$file" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                cwd_diff_index=0; 
            fi

            if [ $index_diff_repo = 0 ] && [ $cwd_diff_repo = 0 ] && [ $cwd_diff_index = 0 ]
            then 
                echo "girt-rm: error: '"$file"' in index is different to both to the working file and the repository";
                exit 1;

            elif [ $index_diff_repo = 0 ]
            then
                echo "girt-rm: error: '"$file"' has staged changes in the index";
                exit 1;
            elif [ $cwd_diff_repo = 0 ]
            then 
                echo "girt-rm: error: '"$file"' in the repository is different to the working file";
                exit 1;
            fi
        fi

        # checking for cached option
        if [ "$1" != "--force" ]
        then
            # checking for unsaved changes in .girt/index (#index vs commit)
            diff -s ".girt/index/$file" ".girt/commit_"$prev_commit_no"/"$file"" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                index_diff_repo=0;
            fi

            # checking for unsaved changes in .girt/index  (#cwd vs index)
            diff -s "./"$file"" ".girt/index/$file" >/dev/null 2>/dev/null;
            if [ $? -ne 0 ] # NOT same file content
            then 
                cwd_diff_index=0;
            fi

            if [ $index_diff_repo = 0 ] && [ $cwd_diff_index = 0 ]
            then 
                echo "girt-rm: error: '"$file"' in index is different to both to the working file and the repository";
                exit 1;
            fi
        fi
    fi

    if [ -f .girt/index/"$file" ]
    then
    
        # remove file
        #echo "removing ./girt/index/"$file"";
        rm .girt/index/"$file";
    elif [ "$file" != '--force' ] && [ "$file" != '--cached' ] 
    then
        echo "girt-rm: error: '"$file"' is not in the girt repository";    
        exit 1;
    fi
    
    # If the --cached option is specified, the file is removed only from the index, 
    # and not from the current directory.
    if [ "$1" = "--cached" ] || [ "$2" = "--cached" ]  
    then
        :
    else
        if [ -f ./"$file" ]
        then
            #echo "removing ./"$file"";
            rm ./"$file";
        fi
    fi

done
