#!/bin/dash
# Written By Marko Wong (z5309371)
# Girt-add will add files to be tracked by the repository

# Error check: There must be an existing .girt repository
if [ -d .girt ]
then 
    for file in $@
    do
        # Every argument called with the script must be a readable file in the
        # current working directory(cwd) or in the index sub directory
        if [ -f "$file" ] || [ -f .girt/index/"$file" ] 
        then 
            :
        else
            echo "girt-add: error: can not open '"$file"'";
            exit 1;
        fi
    done
else
    echo "girt-add: error: girt repository directory .girt not found"
    exit 1;
fi

# Error check: There must be at least one argument called with the script 
if [ $# -lt 1 ]
then
    echo "usage: girt-add <filenames>"
    exit 1;
fi

for file in $@
do
    # Add the file if it exists in the cwd
    if [ -f "$file" ] 
    then 
        cp "$file" ".girt/index";

    # Remove the file if it is not in cwd but in .girt/index as it means the 
    # file has been deleted
    elif [ -f .girt/index/"$file" ] 
    then
        rm .girt/index/"$file";
    else
        echo "girt-add: error: can not open '"$file"'";
        exit 1;
    fi
done
exit 0;
