#!/bin/dash

if [ -d .girt ]
then :
else 
    echo "girt-commit: error: girt repository directory .girt not found"
    exit 1;
fi

if [ -d .girt/commit_0 ]
then
    :
else
    echo "girt-branch: error: this command can not be run until after the first commit"
    exit 1;
fi

if [ $# -eq 1 ]
then
    cwb=$(cat .girt/branches/current_working_branch.txt);
    #echo "switch from "$cwb"";
    # valid branch
    if [ -d .girt/branches/"$1" ]
    then 
        if [ "$1" = "$cwb" ]
        then
            echo "Already on '"$1"'";
            exit 1;
        fi
    
        # sync the branch you are swtiching from with cwd
        for current_files in ./*
        do
            if [ -f "$current_files" ]
            then
                current_file_name=$(basename "$branch_files");
                #echo "copying "$current_files" to .girt/branches/"$cwb"/"$current_file_name"";
                cp "$current_files" .girt/branches/"$cwb"/"$current_file_name";
            fi
        done
        #sync the commits asscoicated with that branch
        cd .girt;
        for commit_file in *
        do
            #echo "commit file is "$commit_file""
            if [ -d "$commit_file" ] && echo "$commit_file" | egrep -q '^commit_.*'
            then 
                cp -R "$commit_file" branches/"$cwb";
            fi
        done
        cd ..;

        #calculate the latest commit number for the branch we are switching from
        commit_no=0;
        while [ -d ".girt/branches/"$cwb"/commit_"$commit_no"" ] 
        do
            commit_no=$(( $commit_no + 1 ));
        done
        latest_cwb_commit_no=$(( $commit_no - 1 ));

        #calculate the latest commit number for the branch we are switching to
        commit_no=0;
        while [ -d ".girt/branches/"$1"/commit_"$commit_no"" ] 
        do
            commit_no=$(( $commit_no + 1 ));
        done
        latest_new_b_commit_no=$(( $commit_no - 1 ));

        # detect any the diff between the latest commits of branches
        difference_detected=1;
        no_files_in_cwb_commit=0;
        for file_check in .girt/branches/"$cwb"/commit_"$latest_cwb_commit_no"
        do
            if [ -f "$file_check" ]
            then
                file_name=$(basename "$file_check");
                #echo "file_name is "$file_name"";
                #echo "comparing "$file_check"  to .girt/commit_"$prev_commit_no"/"$file_name"";
                diff -s "$file_check" ".girt/branches/"$1"/commit_"$latest_new_b_commit_no"" >/dev/null 2>/dev/null;
                if [ $? -ne 0 ] #same file content
                then #1 or 2 so different file content or error like file not found
                    difference_detected=0;
                    #echo "Difference detected"
                fi
            
                no_files_in_cwb_commit=$(( $no_files_in_cwb_commit + 1 ));
            fi
        done

        # count the number of files in cwd latest commit
        no_files_in_new_b_commit=0;
        for file_check in .girt/commit_"$prev_commit_no"/*
        do
            if [ -f "$file_check" ]
            then
                no_files_in_new_b_commit=$(( $no_files_in_new_b_commit + 1 ));
            fi
        done

        if [ $(( $no_files_in_new_b_commit - $no_files_in_cwb_commit )) -ne 0 ]
        then 
            difference_detected=0;
        fi

        #remove all files in cwd to be updated with new branch
        for files in ./*
        do
            if [ -f "$files" ]
            then
                file_name=$(basename "$files");
                rm "$files";
            fi
        done

        if [ "$difference_detected" -eq 0 ]
        then
            #echo "difference_detected";
            # update branch (the one we are switching to) with it's own commit
            for branch_files in .girt/branches/"$1"/commit_"$latest_new_b_commit_no"/*
            do
                if [ -f "$branch_files" ]
                then
                    branch_file_name=$(basename "$branch_files");
                    cp "$branch_files" ./"$branch_file_name" ;
                fi
            done

        # elif [ diff from all three places  ] 
        # then 
        #     echo" error overwrite error";
        #     exit 1;

        # just switch
        # sync cwd with the branch you are switching to
        else 
            for branch_files in .girt/branches/"$1"/*
            do
                if [ -f "$branch_files" ]
                then
                    branch_file_name=$(basename "$branch_files");
                    #echo "copying "$branch_files" to ./"$branch_file_name""; 
                    cp "$branch_files" ./"$branch_file_name" ;
                fi
            done
        fi

        # update the current working branch
        echo "$1" > .girt/branches/current_working_branch.txt;
        echo "Switched to branch '"$1"'";
    else
        echo "girt-checkout: error: unknown branch '"$1"'";
    fi
else
    echo "usage: girt-checkout <branch>"
fi
