#!/bin/dash

if [ -d .girt ]
then :
else 
    echo "girt-commit: error: girt repository directory .girt not found"
    exit 1;
fi

if [ -d .girt/commit_0 ]
then
    :
else
    echo "girt-branch: error: this command can not be run until after the first commit"
    exit 1;
fi

if [ $# -eq 1 ]
then
    cwb=$(cat .girt/branches/current_working_branch.txt);
    #echo "switch from "$cwb"";
    if [ -d .girt/branches/"$1" ]
    then 
        if [ "$1" = "$cwb" ]
        then
            echo "Already on '"$1"'";
            exit 1;
        fi
        # for b_files in .girt/branches/"$1"/*
        # do
        #     if [ -f "$b_files" ]
        #     then
        #         file_name=$(basename "$b_files");
        #         rm "$b_files";
        #     fi
        # done

        # sync the branch you are swtiching from with cwd
        for current_files in ./*
        do
            if [ -f "$current_files" ]
            then
                current_file_name=$(basename "$branch_files");
                cp "$current_files" .girt/branches/"$cwb"/"$current_file_name";
                cp "$current_files" .girt/branches/"$1"/"$current_file_name";
            fi
        done

        #remove all files in cwd to be updated with new branch
        for files in ./*
        do
            if [ -f "$files" ]
            then
                file_name=$(basename "$files");
                rm "$files";
            fi
        done

        # sync cwd with the branch you are switching to
        for branch_files in .girt/branches/"$1"/*
        do
            if [ -f "$branch_files" ]
            then
                branch_file_name=$(basename="$branch_files");
                cp "$branch_files" ./"$branch_file_name" ;
            fi
        done

        # update the current working branch
        echo "$1" > .girt/branches/current_working_branch.txt;
        echo "Switched to branch '"$1"'";
    else
        echo "girt-checkout: error: unknown branch '"$1"'";
    fi
else
    echo "usage: girt-checkout <branch>"
fi
